<template>
    <v-btn
        elevation="24"
        dark
        class="apple-pay-button apple-pay-button-text-pay"
        v-on="on"
        @click.prevent="makeApiCall"
        >
    </v-btn>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

const BACKEND_URL_VALIDATE_SESSION = 'https://{yourServer}/validateSession'
const BACKEND_URL_PAY = 'https://{yourServer}/pay'

// High level configuration options.
var config = {
    payments: {
        acceptedCardSchemes: ['amex', 'masterCard', 'maestro', 'visa', 'mada']
    },
    shop: {
        product_price: 10.0,
        shop_name: 'Demo Shop',
        shop_localisation: {
            currencyCode: 'GBP',
            countryCode: 'GB'
        }
    },
    shipping: {
        GB_region: [{
                label: 'Free Shipping',
                amount: '0.00',
                detail: 'Arrives in 3-5 days',
                identifier: 'freeShipping'
            },
            {
                label: 'Express Shipping',
                amount: '5.00',
                detail: 'Arrives in 1-2 days',
                identifier: 'expressShipping'
            }
        ],
        WORLDWIDE_region: [{
            label: 'Worldwide Standard Shipping',
            amount: '10.00',
            detail: 'Arrives in 5-8 days',
            identifier: 'worldwideShipping'
        }]
    }
}

@Component({})
export default class CreateApplePayVue extends Vue {
    
    /**
     * This is the main method of the script, since here we handle all the Apple Pay
     * events. Here you are able to populate your shipping methods, react to  shipping methods
     * changes, and many other interaction that the user has with the Apple Pay pup-up.
     *
     * @param {object} Apple Pay Session (the one generate on the button click)
     *
     */
    _handleApplePayEvents = function (appleSession: ApplePaySession) {
        // This is the first event that Apple triggers. Here you need to validate the
        // Apple Pay Session from your Back-End
        appleSession.onvalidatemerchant = function (event) {
            _validateApplePaySession(event.validationURL, function (merchantSession) {
                appleSession.completeMerchantValidation(merchantSession)
            })
        }
        
    }


    // @param {string} appleUrl The Apple Pay validation URL generated by Apple
    // @param {function} callback Callback function used to return the server call outcome
    // @return {object} The session payload
    _validateApplePaySession = function (appleUrl: string, callback: any) {
    // I'm using AXIOS to do a POST request to the backend but any HTTP client can be used
    axios
      .post(
        BACKEND_URL_VALIDATE_SESSION,
        {
          appleUrl
        },
        {
          headers: { 'Access-Control-Allow-Origin': '*' }
        }
      )
      .then(function (response) {
        callback(response.data)
      })
  }

    handleApplePayEvents = function (appleSession: any) {
        // apple events
    }

    // Starts the Apple Pay session using a configuration
    startApplePaySession = function (config: any) {
        var applePaySession = new ApplePaySession(6, config)
        handleApplePayEvents(applePaySession)
        applePaySession.begin()
    }

    applePayAvailable = function (): boolean {
        return ApplePaySession && ApplePaySession.canMakePayments()
    }
    
    async makeApiCall() {
        this.startApplePaySession({
            currencyCode: config.shop.shop_localisation.currencyCode,
            countryCode: config.shop.shop_localisation.countryCode,
            merchantCapabilities: [
                'supports3DS',
                'supportsEMV',
                'supportsCredit',
                'supportsDebit'
            ],
            supportedNetworks: config.payments.acceptedCardSchemes,
            shippingType: 'shipping',
            requiredBillingContactFields: [
                'postalAddress',
                'name',
                'phone',
                'email'
            ],
            requiredShippingContactFields: [
                'postalAddress',
                'name',
                'phone',
                'email'
            ],
            total: {
                label: config.shop.shop_name,
                amount: config.shop.product_price,
                type: 'final'
            }
        })
    }
}
</script>

<style scoped>
    .apple-pay-button {
        width: 250px;
        height: 40px;
        display: inline-block;
        -webkit-appearance: -apple-pay-button;
        cursor: pointer;
    }

    .apple-pay-button-text-pay {
        -apple-pay-button-type: pay;
    }
</style>
